name: Deploy to Railway
on:
  push:
    branches:
      - ваша_ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -sSL https://get.railway.app | bash
          export PATH=$PATH:$HOME/.railway/bin

      - name: Login to Railway with Token
        run: railway login -t $RAILWAY_TOKEN

      - name: Deploy to Railway
        run: railway up
